#!/bin/bash
# This script iterates all symlinks in BIN_DIR directory that has the same JDK path as 'java'
# and replaces every symlink with new one that has JDK path as the first argument.
#
# Useful if you want to switch symlinks from OpenJDK to any other JDK.
# author: Zdenek Obst, zdenek.obst-at-gmail.com

BIN_DIR=/usr/bin

if [[ $EUID -ne 0 ]]; then
  echo "You must be root to run this script"
  exit
fi

if [[ -z "$1" ]]; then
  echo "Pass the new JDK home as the first argument, e.g. /opt/java6"
  exit
fi

ACTUAl_JDK_PATH=`ls -l $BIN_DIR/java | awk '{print $11}' | sed 's:\/jre\/bin\/java::g'`
echo "Actual JDK path in symlinks is $ACTUAl_JDK_PATH"

NEW_JDK_PATH=`echo ${1%/}` # remove last slash if needed
echo "New JDK path in symlinks will be $NEW_JDK_PATH"

echo "---------------------------------------"

FILES=`ls -l $BIN_DIR | grep $ACTUAl_JDK_PATH`

ls -l $BIN_DIR | grep $ACTUAl_JDK_PATH | while read file;
do
  FILENAME=`echo $file | awk '{print $9}'`
  SYMLINK=`echo $file | awk '{print $11}'`
  
  #NEWLINK=`echo $SYMLINK | sed "s/[$ACTUAl_JDK_PATH]/[$1]/g"`
  ACT=`echo $ACTUAl_JDK_PATH | sed 's:\/:\\\/:g'` # escape characters for SED
  NEW=`echo $NEW_JDK_PATH | sed 's:\/:\\\/:g'` # escape characters for SED
  
  NEWLINK=`echo $SYMLINK | sed "s/$ACT/$NEW/g"`
  echo "Replacing symlink: $BIN_DIR/$FILENAME -> $NEWLINK"
  rm $BIN_DIR/$FILENAME
  ln -s  $NEWLINK $BIN_DIR/$FILENAME
done
